const blogs = [
  {
    _id: '5a422a851b54a676234d17f7',
    title: 'React patterns',
    author: 'Michael Chan',
    url: 'https://reactpatterns.com/',
    likes: 7,
    __v: 0,
  },
  {
    _id: '5a422aa71b54a676234d17f8',
    title: 'Go To Statement Considered Harmful',
    author: 'Edsger W. Dijkstra',
    url: 'http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html',
    likes: 5,
    __v: 0,
  },
  {
    _id: '5a422b3a1b54a676234d17f9',
    title: 'Canonical string reduction',
    author: 'Edsger W. Dijkstra',
    url: 'http://www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD808.html',
    likes: 12,
    __v: 0,
  },
  {
    _id: '5a422b891b54a676234d17fa',
    title: 'First class tests',
    author: 'Robert C. Martin',
    url: 'http://blog.cleancoder.com/uncle-bob/2017/05/05/TestDefinitions.htmll',
    likes: 10,
    __v: 0,
  },
  {
    _id: '5a422ba71b54a676234d17fb',
    title: 'TDD harms architecture',
    author: 'Robert C. Martin',
    url: 'http://blog.cleancoder.com/uncle-bob/2017/03/03/TDD-Harms-Architecture.html',
    likes: 0,
    __v: 0,
  },
  {
    _id: '5a422bc61b54a676234d17fc',
    title: 'Type wars',
    author: 'Robert C. Martin',
    url: 'http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html',
    likes: 2,
    __v: 0,
  },
]

// 1. All blogs having different number of likes
const blogsAllDifferentLikes = [
  {
    _id: '1',
    title: 'Blog 1',
    author: 'Author A',
    url: 'http://blog1.com',
    likes: 1,
    __v: 0,
  },
  {
    _id: '2',
    title: 'Blog 2',
    author: 'Author B',
    url: 'http://blog2.com',
    likes: 2,
    __v: 0,
  },
  {
    _id: '3',
    title: 'Blog 3',
    author: 'Author C',
    url: 'http://blog3.com',
    likes: 3,
    __v: 0,
  },
  {
    _id: '4',
    title: 'Blog 4',
    author: 'Author D',
    url: 'http://blog4.com',
    likes: 4,
    __v: 0,
  },
  {
    _id: '5',
    title: 'Blog 5',
    author: 'Author E',
    url: 'http://blog5.com',
    likes: 5,
    __v: 0,
  },
  {
    _id: '6',
    title: 'Blog 6',
    author: 'Author F',
    url: 'http://blog6.com',
    likes: 6,
    __v: 0,
  },
]

// 2. Some blogs having same number of likes
const blogsSomeSameLikes = [
  {
    _id: '7',
    title: 'Blog 7',
    author: 'Author A',
    url: 'http://blog7.com',
    likes: 2,
    __v: 0,
  },
  {
    _id: '8',
    title: 'Blog 8',
    author: 'Author B',
    url: 'http://blog8.com',
    likes: 2,
    __v: 0,
  },
  {
    _id: '9',
    title: 'Blog 9',
    author: 'Author C',
    url: 'http://blog9.com',
    likes: 3,
    __v: 0,
  },
  {
    _id: '10',
    title: 'Blog 10',
    author: 'Author D',
    url: 'http://blog10.com',
    likes: 4,
    __v: 0,
  },
  {
    _id: '11',
    title: 'Blog 11',
    author: 'Author E',
    url: 'http://blog11.com',
    likes: 5,
    __v: 0,
  },
  {
    _id: '12',
    title: 'Blog 12',
    author: 'Author F',
    url: 'http://blog12.com',
    likes: 5,
    __v: 0,
  },
]

const listWithOneBlog = [
  {
    _id: '5a422aa71b54a676234d17f8',
    title: 'Go To Statement Considered Harmful',
    author: 'Edsger W. Dijkstra',
    url: 'https://homepages.cwi.nl/~storm/teaching/reader/Dijkstra68.pdf',
    likes: 5,
    __v: 0,
  },
]

// 3. Number of blogs by a specific author is distinct
const blogsDistinctAuthorCounts = [
  {
    _id: '13',
    title: 'Blog 13',
    author: 'Author X',
    url: 'http://blog13.com',
    likes: 1,
    __v: 0,
  },
  {
    _id: '14',
    title: 'Blog 14',
    author: 'Author Y',
    url: 'http://blog14.com',
    likes: 2,
    __v: 0,
  },
  {
    _id: '15',
    title: 'Blog 15',
    author: 'Author Y',
    url: 'http://blog15.com',
    likes: 3,
    __v: 0,
  },
  {
    _id: '16',
    title: 'Blog 16',
    author: 'Author Z',
    url: 'http://blog16.com',
    likes: 4,
    __v: 0,
  },
  {
    _id: '17',
    title: 'Blog 17',
    author: 'Author Z',
    url: 'http://blog17.com',
    likes: 5,
    __v: 0,
  },
  {
    _id: '18',
    title: 'Blog 18',
    author: 'Author Z',
    url: 'http://blog18.com',
    likes: 6,
    __v: 0,
  },
]

// 4. Some authors have same number of blogs
const blogsSomeSameAuthorCounts = [
  {
    _id: '19',
    title: 'Blog 19',
    author: 'Author M',
    url: 'http://blog19.com',
    likes: 1,
    __v: 0,
  },
  {
    _id: '20',
    title: 'Blog 20',
    author: 'Author M',
    url: 'http://blog20.com',
    likes: 2,
    __v: 0,
  },
  {
    _id: '21',
    title: 'Blog 21',
    author: 'Author N',
    url: 'http://blog21.com',
    likes: 3,
    __v: 0,
  },
  {
    _id: '22',
    title: 'Blog 22',
    author: 'Author N',
    url: 'http://blog22.com',
    likes: 4,
    __v: 0,
  },
  {
    _id: '23',
    title: 'Blog 23',
    author: 'Author O',
    url: 'http://blog23.com',
    likes: 5,
    __v: 0,
  },
  {
    _id: '24',
    title: 'Blog 24',
    author: 'Author P',
    url: 'http://blog24.com',
    likes: 6,
    __v: 0,
  },
]

// 5. Total likes on blogs by a specific author is different
const blogsDifferentTotalLikes = [
  {
    _id: '25',
    title: 'Blog 25',
    author: 'Author Q',
    url: 'http://blog25.com',
    likes: 1,
    __v: 0,
  },
  {
    _id: '26',
    title: 'Blog 26',
    author: 'Author Q',
    url: 'http://blog26.com',
    likes: 2,
    __v: 0,
  },
  {
    _id: '27',
    title: 'Blog 27',
    author: 'Author R',
    url: 'http://blog27.com',
    likes: 5,
    __v: 0,
  },
  {
    _id: '28',
    title: 'Blog 28',
    author: 'Author R',
    url: 'http://blog28.com',
    likes: 1,
    __v: 0,
  },
  {
    _id: '29',
    title: 'Blog 29',
    author: 'Author S',
    url: 'http://blog29.com',
    likes: 10,
    __v: 0,
  },
  {
    _id: '30',
    title: 'Blog 30',
    author: 'Author T',
    url: 'http://blog30.com',
    likes: 3,
    __v: 0,
  },
]

// 6. Total likes on blogs by some authors are same
const blogsSomeSameTotalLikes = [
  {
    _id: '31',
    title: 'Blog 31',
    author: 'Author U',
    url: 'http://blog31.com',
    likes: 2,
    __v: 0,
  },
  {
    _id: '32',
    title: 'Blog 32',
    author: 'Author U',
    url: 'http://blog32.com',
    likes: 3,
    __v: 0,
  },
  {
    _id: '33',
    title: 'Blog 33',
    author: 'Author V',
    url: 'http://blog33.com',
    likes: 5,
    __v: 0,
  },
  {
    _id: '34',
    title: 'Blog 34',
    author: 'Author W',
    url: 'http://blog34.com',
    likes: 1,
    __v: 0,
  },
  {
    _id: '35',
    title: 'Blog 35',
    author: 'Author W',
    url: 'http://blog35.com',
    likes: 4,
    __v: 0,
  },
  {
    _id: '36',
    title: 'Blog 36',
    author: 'Author X',
    url: 'http://blog36.com',
    likes: 5,
    __v: 0,
  },
]

module.exports = {
  blogs,
  listWithOneBlog,
  blogsAllDifferentLikes,
  blogsSomeSameLikes,
  blogsDistinctAuthorCounts,
  blogsSomeSameAuthorCounts,
  blogsDifferentTotalLikes,
  blogsSomeSameTotalLikes,
}
